version: '3'
services:
  ue:
    image: docker_ueransim_ue
    container_name: ue
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      subnet_ran:
        ipv4_address: 10.1.1.2
networks:
  subnet_ran:
    ipam:
      config:
        - subnet: 10.1.1.0/24
